CREATE TABLE "get_started_submissions" (
	"id" serial PRIMARY KEY NOT NULL,
	"session_id" text NOT NULL,
	"submission_id" text,
	"status" text DEFAULT 'in_progress' NOT NULL,
	"checkout_session_id" text,
	"website_progress_id" integer,
	"website_language" text DEFAULT 'en' NOT NULL,
	"business_type" text,
	"website_goals" jsonb,
	"website_goal_other" text,
	"suggested_template" text,
	"suggested_structure" jsonb,
	"suggested_addons" jsonb,
	"design_direction" text,
	"full_name" text,
	"email" text NOT NULL,
	"contact_phone" text,
	"document_type" text,
	"vat_number" text,
	"city" text,
	"street" text,
	"street_number" text,
	"postal_code" text,
	"selected_plan" text,
	"billing_period" text,
	"selected_addons" jsonb,
	"business_name" text,
	"business_description" text,
	"services" text,
	"had_website_before" text,
	"previous_website_platform" text,
	"self_description" text,
	"biggest_concerns" jsonb,
	"heard_about_us" jsonb,
	"confirmed_pages" jsonb,
	"pages_notes" text,
	"website_content" text,
	"success_vision" text,
	"media_urls" jsonb,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "get_started_submissions_session_id_unique" UNIQUE("session_id")
);
--> statement-breakpoint
ALTER TABLE "get_started_submissions" ADD CONSTRAINT "get_started_submissions_website_progress_id_website_progress_id_fk" FOREIGN KEY ("website_progress_id") REFERENCES "public"."website_progress"("id") ON DELETE no action ON UPDATE no action;